core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sqli.urls'))
]

sqli/urls.py
from django.urls import path

from . import views


app_name = 'sqli'



urlpatterns = [
    path('', views.LandingPageView.as_view(), name='landing'),
    path('sqli', views.EmployeeListView.as_view(), name='employee-list'),
    path('sqli/create/', views.CreateEmployeeView.as_view(), name='employee-create'),
    path('sqli/details/', views.EmployeeDetailsView.as_view(), name='details'),
    path('sqli/details/secured', views.EmployeeDetailsSecuredView.as_view(), name='details-secured'),
    path('chat-room/', views.ChatRoomView.as_view(), name='chat-room')
]

sqli/models.py
from django.db import models


class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    department = models.CharField(max_length=100)

    def __str__(self) -> str:
        return '{} {}'.format(
            self.first_name,
            self.last_name
        )
    

class ChatRoom(models.Model):
    message = models.TextField(max_length=1000) 

    sender = models.CharField(
        max_length=1000
    )

    def __str__(self) -> str:
        return self.sender

sqli/forms.py
from django import forms

from .models import Employee, ChatRoom


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = [
            'first_name',
            'last_name',
            'department'
        ]


class ChatRoomForm(forms.ModelForm):
    class Meta:
        model = ChatRoom
        fields = [
            'message',
            'sender'
        ]

sqli/views.py
from typing import Any
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.views.generic import TemplateView, CreateView
from django.urls import reverse_lazy
from django.db import connection

from .models import Employee, ChatRoom
from .forms import EmployeeForm, ChatRoomForm


class EmployeeListView(TemplateView):
    template_name = 'employee-list.html'

    def __init__(self, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.employees = Employee.objects.all()

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        return {'self': self}


class CreateEmployeeView(CreateView):
    form_class = EmployeeForm
    template_name = 'employee-create.html'
    success_url = reverse_lazy('sqli:employee-create')

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        self.form = self.get_form()
        return {'self': self}
    


class EmployeeDetailsView(TemplateView):
    template_name = 'employee-details.html'

    def get(self, request, *args: Any, **kwargs):
        self.employee_id = request.GET.get('employee_id', None)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        sql = 'SELECT * FROM sqli_employee WHERE id = ' + self.employee_id + ' LIMIT 1'
        self.employee = Employee.objects.raw(sql)[0]
        return {'self': self}


class EmployeeDetailsSecuredView(TemplateView):
    template_name = 'employee-details.html'

    def get(self, request, *args: Any, **kwargs):
        self.employee_id = request.GET.get('employee_id', None)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        sql = 'SELECT * FROM sqli_employee WHERE id = %s LIMIT 1'
        employee = Employee.objects.raw(sql, [self.employee_id])
        self.employee = employee[0] if len(employee) > 0 else None
        return {'self': self}


class LandingPageView(TemplateView):
    template_name = 'landing.html'


class ChatRoomView(CreateView):
    template_name = 'chat-room.html'
    form_class = ChatRoomForm

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        sql = "INSERT INTO sqli_chatroom (message, sender) VALUES ('%s', '%s')" % (request.POST.get('message'), request.POST.get('sender'))
        print(sql)
        with connection.cursor() as cursor:
            cursor.execute(sql)

        connection.commit()

        return HttpResponseRedirect(reverse_lazy('sqli:chat-room'))

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        self.chats = ChatRoom.objects.all()
        self.form = self.get_form()
        return {'self': self}

templates/chat-room.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <style>
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    .container {
      max-width: 1000px;
      margin: auto;
      padding: 2em;
    }

    .chat {
      border: 1px solid black;
      padding: 1em;
      max-width: 400px;
      text-align: right;
    }

    .content {
      margin-bottom: 1rem;
    }

    .message {
      background-color: rgba(128, 128, 128, 0.651);
      padding: 0.5em;
      border-radius: 5px;
      width: max-content;
      margin-left: auto;
    }

  </style>
</head>
<body class="container">
  <div class="chat">
    {% for chat in self.chats %}
      <div class="content">
        <p class="sender">{{ chat.sender }}</p>
        <p class="message">{{ chat.message|safe }}</p>
      </div>
    {% endfor %}
  </div>


  <form method="post">
    {% csrf_token %}
    <div>
      <label for="sender">Sender: </label>
      <input type="text" name="sender" id="sender" required="required"/>
    </div>

    <div>
      <label for="message">Message:</label> <br>
      <textarea name="message" id="message" cols="30" rows="10" required="required"></textarea>
    </div>
    <input type="submit" value="Send">
  </form>
</body>
</html>

templates/employee-create.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>

  <style>
    .link {
      border: 1px solid rgb(29, 29, 194);
      background-color: rgb(29, 29, 194);
      color: white;
      text-decoration: none;
      padding: 0.5em;
      border-radius: 3px;
      display: block;
      width: max-content;
      margin: auto;
      margin-bottom: 2rem;
    }

    .mb {
      margin-bottom: 1rem;
    }

    .center {
      max-width: max-content;
      margin: auto;
    }

    .text-center {
      text-align: center;
    }
  </style>
</head>
<body>
  <div class="center text-center">
    <form class="mb" method="POST">
      {% csrf_token %}
      <div class="mb">
        <label for="first_name">First Name</label> <br />
        {{self.form.first_name}}
      </div>
      <div class="mb">
        <label for="last_name">Last Name</label> <br />
        {{self.form.last_name}}
      </div>
      <div class="mb">
        <label for="first_name">Department</label> <br />
        {{self.form.department}}
      </div>
      <input type="submit" value="Create">
    </form>
    <div>
      <a class="link" href="{% url 'sqli:employee-list' %}">List</a>
    </div>
  </div>
</body>
</html>

templates/employee-details.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% if self.employee %}
    <h1>First Name: {{ self.employee.first_name }}</h1>
    <h1>Last Name: {{ self.employee.last_name }}</h1>
    <h1>Department: {{ self.employee.department }}</h1>
  {% else %}
    <h1>Employee is not available.</h1>
  {% endif %}
  

  <a href="{% url 'sqli:employee-list' %}">List</a>
</body>
</html>

templates/employee-list.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SQLi</title>

  <style>
    table,
    th,
    td{
      border: 2px solid black;
      border-collapse: collapse;
    }

    table {
      margin: auto;
    }

    th,
    td {
      padding: 0.5em;
      min-width: 200px;
    }

    .link {
      border: 1px solid rgb(29, 29, 194);
      background-color: rgb(29, 29, 194);
      color: white;
      text-decoration: none;
      padding: 0.5em;
      border-radius: 3px;
      display: block;
      width: max-content;
      margin: auto;
      margin-bottom: 2rem;
    }

    .center {
      text-align: center;
    }
    
    .mr {
      margin-right: 1rem;
    }
  </style>
</head>
<body>
  <div class="">
    <a class="link" href="{% url 'sqli:employee-create' %}">Add Employee</a>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th class="header">First Name</th>
        <th class="header">Last Name</th>
        <th class="header">Department</th>
        <th class="header"></th>
      </tr>
    </thead>
    <tbody>
      {% for employee in self.employees %}
        <tr>
          <td class="data">{{ employee.first_name }}</td>
          <td class="data">{{ employee.last_name }}</td>
          <td class="data">{{ employee.department }}</td>
          <td class="data center">
            <a class="mr" href="{% url 'sqli:details' %}?employee_id={{ employee.id }}">
              Unsecured
            </a>
            <a href="{% url 'sqli:details-secured' %}?employee_id={{ employee.id }}">
              Secured
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</body>
</html>

templates/landing.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Injection</title>
</head>
<body>
  <a href="{% url 'sqli:employee-list' %}">SQLi</a>
  <a href="{% url 'sqli:chat-room' %}">XSS</a>
</body>
</html>